### ISSUE TITLE
cordova prepare error

### ISSUE THREAD

**Issue by ghost** [saeedvaziry/vue-f7-cordova-wordpress-app#1]
Hi,

Hope you are all well !

I have the following error when trying to execute the 'cordova prepare' command:

```bash
src-cordova % cordova prepare      
Current working directory is not a Cordova-based project.
```

Any idea how to fix it ? Thanks in advance for any help or insights.

Cheers,
X

**Comment by saeedvz** [comment]
Hi,
Why do you running that command?

**Comment by ghost** [comment]
Which command should I use ?

**Comment by saeedvz** [comment]
Please see https://github.com/saeedvaziry/vue-f7-cordova-wordpress-app/blob/master/README.md

**Comment by ghost** [comment]
https://github.com/saeedvaziry/vue-f7-cordova-wordpress-app/blob/master/README.md#cordova
it says cordova prepare

**Comment by saeedvz** [comment]
Please be sure that you are running that command inside the project folder

**Comment by ghost** [comment]
I managed to make it work, thanks for your repository

**Comment by saeedvz** [comment]
If you think the documentation is not clear enough please let me know.
Thanks.
